### ISSUE TITLE
Obtain observation data for Hurricane Matthew test case

### ISSUE THREAD

**Issue by jaredalee** [NCAR/i-wrf#47]
## Describe the Task ##
Obtain MADIS or other observation data for the Hurricane Matthew test case (https://www2.mmm.ucar.edu/wrf/OnLineTutorial/CASES/SingleDomain/index.php) that can be used for verification in METplus. This data will be used to calculate some verification statistics using the WRF output of #46. 

### Time Estimate ###
1 day

### Sub-Issues ###
Consider breaking the task down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
Target completion 1 Mar 2024.

### Funding Source ###
7790013

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [ ] Select **component(s)**
- [ ] Select **priority**
- [ ] Select **requestor(s)**

### Projects and Milestone ###
- [ ] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED PROJECT ASSIGNMENT** label
- [ ] Select **Milestone** as the next official version or **Future Versions**

## Task Checklist ##
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Development** issues
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by jaredalee** [comment]
MET's madis2nc utility was used to process metar and raob MADIS files for the Hurricane Matthew test case. Those files are stored here on Derecho/Casper:

/glade/campaign/ral/wsap/i-wrf/data/hurr-matthew/madis/point/metar/netcdf/met_[YYYYMMDD_HHMM].nc
/glade/campaign/ral/wsap/i-wrf/data/hurr-matthew/madis/point/raob/netcdf/met_[YYYYMMDD_HHMM].nc

**Comment by georgemccabe** [comment]
The script that @jaredalee used to run madis2nc can be found on derecho:/glade/u/home/jaredlee/tools/python/MET/run_madis2nc.py

Here are the contents of that script:
```
'''
run_madis2nc.py

Written by: Jared A. Lee (jaredlee@ucar.edu)
Written on: 22 Mar 2024

This script executes a series of calls to MET's madis2nc tool.
'''

import pathlib
import subprocess
import datetime as dt
import pandas as pd

date_str_beg = '20161006_0000'
date_str_end = '20161008_0000'

#obs_type = 'raob'
obs_type = 'metar'
if obs_type == 'raob':
    data_dir = pathlib.Path('/','glade','derecho','scratch','jaredlee','data','madis','point','raob','netcdf')
elif obs_type == 'metar':
    data_dir = pathlib.Path('/','glade','derecho','scratch','jaredlee','data','madis','point','metar','netcdf')

date_fmt = '%Y%m%d_%H%M'
date_beg = dt.datetime.strptime(date_str_beg, date_fmt)
date_end = dt.datetime.strptime(date_str_end, date_fmt)
date_range = pd.date_range(start=date_beg, end=date_end, freq='1h')
n_dates = len(date_range)

## Loop over dates
for dd in range(n_dates):
    date_str = date_range[dd].strftime(date_fmt)
    in_file = data_dir.joinpath(date_str)
    out_file = data_dir.joinpath('met_'+date_str+'.nc')
    print('Reading '+str(in_file))
    print('Writing '+str(out_file))
    subprocess.run(['madis2nc', str(in_file), str(out_file), '-type', obs_type])
```
